-- STQD6324 Assignment 2 (P167345)
-- Cassandra setup and data import

-- I originally planned to write Spark DataFrames directly into Cassandra
-- but I got a dependency error with the Spark Cassandra Connector
-- so I used COPY commands to load the CSV files generated by Spark

-- ============================================================
-- Keyspace
-- ============================================================

CREATE KEYSPACE IF NOT EXISTS assignment2
WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

USE assignment2;

-- ============================================================
-- Tables
-- ============================================================

CREATE TABLE IF NOT EXISTS average_movie_ratings (
    movie_id int PRIMARY KEY,
    movie_title text,
    average_rating double
);

CREATE TABLE IF NOT EXISTS top10_movies (
    movie_id int PRIMARY KEY,
    movie_title text,
    average_rating double
);

-- users who rated at least 50 movies, with their favourite genre
CREATE TABLE IF NOT EXISTS favourite_genres (
    user_id int PRIMARY KEY,
    rating_count int,
    genre text,
    genre_count int
);

CREATE TABLE IF NOT EXISTS users_under_20 (
    user_id int PRIMARY KEY,
    age int,
    gender text,
    occupation text,
    zip_code text
);

CREATE TABLE IF NOT EXISTS scientist_users_30_40 (
    user_id int PRIMARY KEY,
    age int,
    gender text,
    occupation text,
    zip_code text
);

-- double check all tables are created
DESCRIBE TABLES;

-- ============================================================
-- Import CSV files
-- CSV path: /home/maria_dev/assignment2/cassandra_csv
-- ============================================================

COPY average_movie_ratings (movie_id, movie_title, average_rating)
FROM '/home/maria_dev/assignment2/cassandra_csv/average_movie_ratings.csv'
WITH HEADER = TRUE;

COPY top10_movies (movie_id, movie_title, average_rating)
FROM '/home/maria_dev/assignment2/cassandra_csv/top10_movies.csv'
WITH HEADER = TRUE;

COPY favourite_genres (user_id, rating_count, genre, genre_count)
FROM '/home/maria_dev/assignment2/cassandra_csv/favourite_genres.csv'
WITH HEADER = TRUE;

COPY users_under_20 (user_id, age, gender, occupation, zip_code)
FROM '/home/maria_dev/assignment2/cassandra_csv/users_under_20.csv'
WITH HEADER = TRUE;

COPY scientist_users_30_40 (user_id, age, gender, occupation, zip_code)
FROM '/home/maria_dev/assignment2/cassandra_csv/scientist_users_30_40.csv'
WITH HEADER = TRUE;

-- ============================================================
-- Validation
-- ============================================================

SELECT COUNT(*) FROM average_movie_ratings;
SELECT COUNT(*) FROM top10_movies;
SELECT COUNT(*) FROM favourite_genres;
SELECT COUNT(*) FROM users_under_20;
SELECT COUNT(*) FROM scientist_users_30_40;

-- preview some records to check the data looks right
SELECT * FROM top10_movies LIMIT 10;
SELECT * FROM favourite_genres LIMIT 10;
SELECT * FROM users_under_20 LIMIT 10;
SELECT * FROM scientist_users_30_40 LIMIT 10;
